#!/usr/bin/env python3
with open('./README.md', 'w') as f:
	title = input("Title:")
	shit = input("题目描述:")
	fuck = input("输入描述:")
	damn = input("输出描述:")
	f.write("# " + title + '  \n')
	f.write("**" + "题目描述:" + '**' + '  \n')
	f.write(shit + '  \n')
	f.write('\n')
	f.write("**" + "输入描述:" + '**' + '  \n')
	f.write(fuck + '  \n')
	f.write('\n')
	f.write("**" + "输出描述:" + '**' + '  \n')
	f.write(damn + '  \n')
	f.write('\n')
	f.write("**" + "样例输入：" + '**' + '  \n')
	f.write('```' + '```  \n')
	f.write("**" + "样例输出：" + '**' + '  \n')
	f.write('```' + '```  \n')
	f.write('\n')
